version: "3.7"
services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=ticket_booking_app
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - postgres
  ticket-booking-app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: "./"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgressql://postgres:5432/ticket_booking_app
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - postgres
volumes:
  postgres:
networks:
  postgres:
    driver: bridge
